module.exports = {
  "ALIVE_IMG": "",
  "FOOT": "©𝐌𝐑 𝐌𝐀𝐍𝐔𝐋 𝐎𝐅𝐂 💚",
  "PREFIX": ".",
  "AUTO_READ_STATUS": "true",
  "MODE": "public",
  "BOT_NUMBER": "94720385508",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "true",
  "ANTI_BAD": "true",
  "ANTI_BOT": "false",
  "ANTI_CALL": "true",
  "ANTI_LINK": "true",
  "ANTI_PHOTO": "true",
  "ANTI_STICKER": "warn",
  "ANTI_DELETE": true,
  "DELETEMSGSENDTO": "94720385508",
  "ALWAYS_ONLINE": "true",
  "MOROCCO_BLOCK": "false",
  "OWNER_NAME": "©𝐌𝐑 𝐌𝐀𝐍𝐔𝐋 𝐎𝐅𝐂 💚",
  "OWNER_NUMBER": "94742274855",
  "AUTO_BIO": "true",
  "AUTO_TYPING": "true",
  "AUTO_RECORDING": "true",
  "WARN_COUNT": "3",
  "AI_MODE": true,
};
